version: '2'

services:
  mosquitto-sgx:
    image: enclaive/mosquitto
    container_name: "mosquitto-sgx"
    build:
      context: .
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
  mosquitto:
    image: enclaive/mosquitto
    container_name: "mosquitto"
    entrypoint: ""
    build:
      context: .
